version: "3.3"  # optional since v1.27.0
services:
    web:
        build: .
        ports: 
            - 3000:3000
        command: bundle exec rails s -b 0.0.0.0
        volumes:
            - bundle:/app/.bundle
            - .:/app

volumes:
  bundle:
